name: hq_svc
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud//pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.0=hac33072_0
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - dav1d=1.2.1=hd590300_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=7.0.0=gpl_h9c209ab_101
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gmp=6.3.0=h59595ed_1
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h59595ed_1003
  - harfbuzz=8.4.0=h3d44ed6_0
  - icu=73.2=h59595ed_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.40=h55db66e_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libass=0.17.1=h8fe9dca_1
  - libdrm=2.4.120=hd590300_0
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_7
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libglib=2.80.2=hf974151_0
  - libgomp=13.2.0=h77fa898_7
  - libhwloc=2.10.0=default_h2fb2949_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libopenvino=2024.1.0=h2da1b83_5
  - libopenvino-auto-batch-plugin=2024.1.0=hb045406_5
  - libopenvino-auto-plugin=2024.1.0=hb045406_5
  - libopenvino-hetero-plugin=2024.1.0=h5c03a75_5
  - libopenvino-intel-cpu-plugin=2024.1.0=h2da1b83_5
  - libopenvino-intel-gpu-plugin=2024.1.0=h2da1b83_5
  - libopenvino-intel-npu-plugin=2024.1.0=he02047a_5
  - libopenvino-ir-frontend=2024.1.0=h5c03a75_5
  - libopenvino-onnx-frontend=2024.1.0=h07e8aee_5
  - libopenvino-paddle-frontend=2024.1.0=h07e8aee_5
  - libopenvino-pytorch-frontend=2024.1.0=he02047a_5
  - libopenvino-tensorflow-frontend=2024.1.0=h39126c6_5
  - libopenvino-tensorflow-lite-frontend=2024.1.0=he02047a_5
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libsqlite=3.45.3=h2797004_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtasn1=4.19.0=h166bdaf_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=hd590300_0
  - libvpx=1.14.0=h59595ed_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.12.6=h232c23b_2
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.5=h59595ed_0
  - nettle=3.9.1=h7ab15ed_0
  - ocl-icd=2.3.2=hd590300_1
  - openh264=2.4.1=h59595ed_0
  - openssl=3.3.0=hd590300_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.43=hcad00b1_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - python=3.9.15=hba424b6_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=69.5.1=pyhd8ed1ab_0
  - snappy=1.2.0=hdb0a2a9_1
  - svt-av1=2.0.0=h59595ed_0
  - tbb=2021.12.0=h00ab1b0_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - pip:
      - absl-py==2.1.0
      - accelerate==0.24.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.8
      - anyio==4.3.0
      - argcomplete==3.3.0
      - argparse==1.4.0
      - asteroid==0.7.0
      - asteroid-filterbanks==0.4.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - audiomentations==0.35.0
      - audioread==3.0.1
      - audiosr==0.0.7
      - auraloss==0.4.0
      - babel==2.15.0
      - beartype==0.19.0
      - bibtexparser==2.0.0b7
      - bitarray==2.9.2
      - black==24.1.1
      - braceexpand==0.1.7
      - byol-pytorch==0.8.2
      - cached-property==1.5.2
      - cachetools==5.3.3
      - certifi==2024.2.2
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clldutils==3.22.2
      - cmake==3.29.3
      - colorama==0.4.6
      - colorlog==6.8.2
      - contourpy==1.2.1
      - csvw==3.3.0
      - cycler==0.12.1
      - cython==3.0.10
      - cytoolz==0.12.3
      - datasets==2.20.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - diffsptk==1.0.1
      - diffusers==0.28.0.dev0
      - dill==0.3.8
      - distance==0.1.3
      - distlib==0.3.8
      - dlinfo==1.2.1
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.8.0
      - einx==0.2.2
      - email-validator==2.1.1
      - encodec==0.1.1
      - exceptiongroup==1.2.1
      - fairseq==0.12.2
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - fastdtw==0.3.4
      - ffmpeg-python==0.2.0
      - ffmpy==0.3.2
      - filelock==3.14.0
      - fonttools==4.51.0
      - frechet-audio-distance==0.3.1
      - frozendict==2.4.4
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - future==1.0.0
      - g2p-en==2.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.44.1
      - gradio-client==1.3.0
      - grpcio==1.63.0
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.5
      - humanfriendly==10.0
      - hydra-core==1.0.7
      - idna==3.7
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - inflect==7.2.1
      - iniconfig==2.0.0
      - intervaltree==3.1.0
      - isodate==0.6.1
      - jinja2==3.1.4
      - jiwer==3.0.5
      - joblib==1.4.2
      - json5==0.9.25
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - julius==0.2.7
      - kiwisolver==1.4.5
      - laion-clap==1.1.2
      - language-tags==1.2.0
      - lhotse==1.24.0.dev0+git.ddde5bd.clean
      - librosa==0.9.2
      - lightning-utilities==0.11.2
      - lilcom==1.7
      - lit==18.1.4
      - llvmlite==0.42.0
      - local-attention==1.9.3
      - loguru==0.7.2
      - lxml==5.2.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - mir-eval==0.7
      - modelscope==1.21.0
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - nnaudio==0.3.3
      - nox==2024.4.15
      - numba==0.59.1
      - numpy==1.23.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - nvitop==1.3.2
      - omegaconf==2.0.6
      - openai-whisper==20231117
      - orjson==3.10.3
      - packaging==24.0
      - pandas==2.2.2
      - pathspec==0.12.1
      - pb-bss-eval==0.0.2
      - pedalboard==0.9.5
      - peft==0.12.0
      - pesq==0.0.4
      - phonemizer==3.2.1
      - pillow==10.3.0
      - platformdirs==4.2.1
      - pluggy==1.5.0
      - pooch==1.8.1
      - portalocker==2.8.2
      - praat-parselmouth==0.4.3
      - progressbar==2.5
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptwt==0.1.8
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydub==0.25.1
      - pygments==2.18.0
      - pylatexenc==2.10
      - pymcd==0.2.1
      - pyparsing==3.1.2
      - pypesq==1.2.4
      - pypinyin==0.48.0
      - pysptk==0.2.2
      - pystoi==0.4.1
      - pytest==8.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytorch-lightning==2.2.4
      - pytorch-msssim==1.0.0
      - pytorch-ranger==0.1.1
      - pytz==2024.1
      - pywavelets==1.6.0
      - pyworld==0.3.4
      - pyyaml==6.0.1
      - rapidfuzz==3.10.1
      - rdflib==7.0.0
      - referencing==0.35.1
      - regex==2024.5.10
      - requests==2.32.3
      - resampy==0.4.3
      - resemblyzer==0.1.4
      - rfc3986==1.5.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - ruff==0.4.5
      - sacrebleu==2.4.2
      - safetensors==0.4.3
      - scikit-learn==1.4.2
      - scipy==1.10.1
      - segments==2.2.1
      - semantic-version==2.10.0
      - sentry-sdk==2.1.1
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - starlette==0.37.2
      - svgwrite==1.4.3
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - tgt==1.5
      - threadpoolctl==3.5.0
      - tiktoken==0.6.0
      - timm==1.0.3
      - tokenizers==0.13.3
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.0.1+cu118
      - torch-optimizer==0.1.0
      - torch-stoi==0.2.1
      - torchaudio==2.0.2+cu118
      - torchcrepe==0.0.18
      - torchlibrosa==0.1.0
      - torchlpc==0.4
      - torchmetrics==0.11.4
      - torchvision==0.15.2+cu118
      - tqdm==4.66.4
      - transformers==4.30.2
      - tree==0.2.4
      - triton==2.0.0
      - typeguard==4.2.1
      - typer==0.12.3
      - typing==3.7.4.3
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - ujson==5.10.0
      - unidecode==1.3.8
      - uritemplate==4.1.1
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - vector-quantize-pytorch==1.12.5
      - virtualenv==20.26.1
      - wandb==0.17.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - webdataset==0.2.86
      - webrtcvad==2.0.10
      - websockets==11.0.3
      - werkzeug==3.0.3
      - wget==3.2
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.18.1
prefix: /home/bbs/miniconda3/envs/controlsvc_eval
